### ISSUE TITLE
verifier not found

### ISSUE THREAD

**Issue by qt3m45su0najc7** [tumblr/pytumblr#111]
Hello,

Interactive_console.py is failing with **verifier not found** for my url, the redirect once authorization is completed.  I was wondering if oauth_ object is still able to properly parse the url to extract the verifier. I haven't seen another open issue on verifier, but the verifier is in the redirect url input.

**Test set:**
_python setup.py test_ runs without raising an error.

The url I submitted is (changes with each execution):

https://www.yahoo.com/?oauth_token=lMsomelettersandnumbersI8DSPkPToWezkEECTcyuWORc0&oauth_verifier=M2CAav9ffwXKsTRNKUgYVpnF0NSAedryRERgbtcd7EPyGHW0wO#_=_

The &oauth_verifier= string is present and pasted as requested in terminal running interactive_console.py,

At this point, code is executed
    oauth_response = oauth_session.parse_authorization_response(redirect_response)
    verifier = oauth_response.get('oauth_verifier')

Verifier contains 'None'

**Here is the traceback:**
	Traceback (most recent call last):
	  File "c:\Users\albert\Desktop\rxd\tumblr oauth\interactive_console.py", line 83, in <module>
		tokens = new_oauth(yaml_path)
	  File "c:\Users\albert\Desktop\rxd\tumblr oauth\interactive_console.py", line 60, in new_oauth
		oauth_tokens = oauth_session.fetch_access_token(access_token_url)
	  File "C:\Program Files\Python36\lib\site-packages\requests_oauthlib\oauth1_session.py", line 319, in fetch_access_token
		raise VerifierMissing('No client verifier has been set.')
	requests_oauthlib.oauth1_session.VerifierMissing: No client verifier has been set.
	
**Miscellaneous:**
Code used was from Latest commit 250ad07  on Oct 14, 2017
Version info:
3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)]
Windows system.

Appreciate any suggestions.  No urgency. Python neophyte.

**Comment by qt3m45su0najc7** [comment]
I'm closing.  Not resolved. No contact.  I hope it's just my environment or usage and the code still works as posted.
