### ISSUE TITLE
"before" param for posts is not allowed

### ISSUE THREAD

**Issue by ievans3024** [tumblr/pytumblr#119]
Python 3.7.1
PyTumblr 0.0.8
```
>>> import pytumblr
>>> client = pytumblr.TumblrRestClient(TUMBLR_CLIENT_KEY, TUMBLR_CLIENT_SECRET, TUMBLR_TOKEN, TUMBLR_TOKEN_SECRET)
>>> client.posts('staff', before=1541048400)  # November 1, 2018 at 12:00 am
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ian/PycharmProjects/Stash/venv/lib/python3.7/site-packages/pytumblr/helpers.py", line 47, in add_dot_tumblr
    return fn(*args, **kwargs)
  File "/home/ian/PycharmProjects/Stash/venv/lib/python3.7/site-packages/pytumblr/__init__.py", line 133, in posts
    return self.send_api_request("get", url, kwargs, ['id', 'tag', 'limit', 'offset', 'reblog_info', 'notes_info', 'filter', 'api_key'], True)
  File "/home/ian/PycharmProjects/Stash/venv/lib/python3.7/site-packages/pytumblr/__init__.py", line 558, in send_api_request
    validate_params(valid_parameters, params)
  File "/home/ian/PycharmProjects/Stash/venv/lib/python3.7/site-packages/pytumblr/helpers.py", line 29, in validate_params
    raise Exception("{0} are not allowed fields".format(field_strings))
Exception: before are not allowed fields
```
Looking at the code, it looks like the allowed params defined in this package do not line up with the params defined in the API docs

**Comment by tehgarra** [comment]
what platform are you using it on? i haven't been able to get the setup.py test to work at all

**Comment by ievans3024** [comment]
@tehgarra installed via pip on arch linux.

**Comment by tehgarra** [comment]
> 
> 
> @tehgarra installed via pip on arch linux.

thanks, i will try installing that. do you use a desktop environment by any chance?
