### ISSUE TITLE
UnicodeDecodeError when creating photos with unicode filenames

### ISSUE THREAD

**Issue by jdp** [tumblr/pytumblr#58]
The `TumblrRestClient.create_photo` method raises a `UnicodeDecodeError` when the filename is a `unicode` instance. Coercing it to `str` fixes the problem. Here's an example traceback:

``` python
>>> import pytumblr
>>> t = pytumblr.TumblrRestClient(consumer_key, consumer_secret, oauth_token, oauth_token_secret)
>>> filename = u"/path/to/file"
>>> t.create_photo(blog_name, data=filename)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/justin/.virtualenvs/machino/lib/python2.7/site-packages/pytumblr/helpers.py", line 44, in add_dot_tumblr
    return fn(*args, **kwargs)
  File "/Users/justin/.virtualenvs/machino/lib/python2.7/site-packages/pytumblr/__init__.py", line 281, in create_photo
    return self._send_post(blogname, kwargs)
  File "/Users/justin/.virtualenvs/machino/lib/python2.7/site-packages/pytumblr/__init__.py", line 505, in _send_post
    return self.send_api_request("post", url, params, valid_options)
  File "/Users/justin/.virtualenvs/machino/lib/python2.7/site-packages/pytumblr/__init__.py", line 538, in send_api_request
    return self.request.post(url, params, files)
  File "/Users/justin/.virtualenvs/machino/lib/python2.7/site-packages/pytumblr/request.py", line 56, in post
    return self.post_multipart(url, params, files)
  File "/Users/justin/.virtualenvs/machino/lib/python2.7/site-packages/pytumblr/request.py", line 101, in post_multipart
    content_type, body = self.encode_multipart_formdata(params, files)
  File "/Users/justin/.virtualenvs/machino/lib/python2.7/site-packages/pytumblr/request.py", line 137, in encode_multipart_formdata
    body = CRLF.join(L)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)
>>> t.create_photo(blog_name, data=str(filename))
{u'id': ...}
```

**Comment by rbreu** [comment]
I've run into the same problem when trying to read posts filtered by a tag containing umlauts. Fixing the pytumblr code seems straight forward enough (the params must be encoded strings when passed to urlencode), but when I fix this, I'm running into the same problem with oauth. The ouauth.Client.request method takes the utf8+url-encoded string, then decodes it again into unicode strings, and fails to encode them when passing them once again to urlencode. :(

Fiddling with the oauth code leads to 401s, but I have to admit I know nothing about oauth stuff. Googling suggests that the unicode problem should have been fixed in oauth, no-one else seems to be having problems lately, and I'm using the latest version from pypi, so this is all very confusing. If anyone is interested in looking into this problem with me, let me know.

(I guess this unicode stuff might be a lot easier in Python 3...)

**Comment by rbreu** [comment]
Okay, the encoding problem is NOT fixed in oauth. There's a pull request that's never been accpted, it's in this fork:  https://github.com/romke/python-oauth2

With that fork and my changes, I can now successfully filter by tags with umlauts. \o/ I'd be willing to go through the pytumblr code and submit a pull request, if people are interested. I'm not sure of how much use it is to people using the release version of oauth2. Seeing that oauth2 seems to have been unmaintained for years now, I second the suggestion in issue #42 to switch to oauthlib instead.

**Comment by jasonpenny** [comment]
A recent PR that was merged looks like it works with unicode tags and filenames
