### ISSUE TITLE
TypeError write() argument 1 must be string or read-only buffer, not bytearray

### ISSUE THREAD

**Issue by areinbee** [tumblr/pytumblr#68]
The code is client.create_audio(tumblr_username, state="published", data=file_path) produces the errors below but when I do client.create_text(tumblr_username, state="published", body=file_path), a post is created on tumblr with the text of the file path, which is the correct file path for the audio.

Why might this be happening? 

Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1836, in **call**
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/vmail/handle_calls.py", line 389, in send_message
    t_client.create_audio(tumblr_username, state="published", data=str_file)
  File "build/bdist.linux-x86_64/egg/pytumblr/helpers.py", line 47, in add_dot_tumblr
    return fn(_args, *_kwargs)
  File "build/bdist.linux-x86_64/egg/pytumblr/**init**.py", line 387, in create_audio
    return self._send_post(blogname, kwargs)
  File "build/bdist.linux-x86_64/egg/pytumblr/__init__.py", line 509, in _send_post
    return self.send_api_request("post", url, params, valid_options)
  File "build/bdist.linux-x86_64/egg/pytumblr/__init__.py", line 542, in send_api_request
    return self.request.post(url, params, files)
  File "build/bdist.linux-x86_64/egg/pytumblr/request.py", line 61, in post
    return self.post_multipart(url, params, files)
  File "build/bdist.linux-x86_64/egg/pytumblr/request.py", line 111, in post_multipart
    content = urllib2.urlopen(r).read()
  File "/usr/lib64/python2.6/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib64/python2.6/urllib2.py", line 391, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.6/urllib2.py", line 409, in _open
    '_open', req)
  File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 1198, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib64/python2.6/urllib2.py", line 1162, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib64/python2.6/httplib.py", line 914, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.6/httplib.py", line 954, in _send_request
    self.send(body)
  File "/usr/lib64/python2.6/httplib.py", line 759, in send
    self.sock.sendall(str)
  File "/usr/lib64/python2.6/ssl.py", line 203, in sendall
    v = self.send(data[count:])
  File "/usr/lib64/python2.6/ssl.py", line 174, in send
    v = self._sslobj.write(data)
TypeError: write() argument 1 must be string or read-only buffer, not bytearray
ERROR:gunicorn.error:Error handling request
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/vmail/handle_calls.py", line 389, in send_message
    t_client.create_audio(tumblr_username, state="published", data=str_file)
  File "build/bdist.linux-x86_64/egg/pytumblr/helpers.py", line 47, in add_dot_tumblr
    return fn(_args, *_kwargs)
  File "build/bdist.linux-x86_64/egg/pytumblr/**init**.py", line 387, in create_audio
    return self._send_post(blogname, kwargs)
  File "build/bdist.linux-x86_64/egg/pytumblr/__init__.py", line 509, in _send_post
    return self.send_api_request("post", url, params, valid_options)
  File "build/bdist.linux-x86_64/egg/pytumblr/__init__.py", line 542, in send_api_request
    return self.request.post(url, params, files)
  File "build/bdist.linux-x86_64/egg/pytumblr/request.py", line 61, in post
    return self.post_multipart(url, params, files)
  File "build/bdist.linux-x86_64/egg/pytumblr/request.py", line 111, in post_multipart
    content = urllib2.urlopen(r).read()
  File "/usr/lib64/python2.6/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib64/python2.6/urllib2.py", line 391, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.6/urllib2.py", line 409, in _open
    '_open', req)
  File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 1198, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib64/python2.6/urllib2.py", line 1162, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib64/python2.6/httplib.py", line 914, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.6/httplib.py", line 954, in _send_request
    self.send(body)
  File "/usr/lib64/python2.6/httplib.py", line 759, in send
    self.sock.sendall(str)
  File "/usr/lib64/python2.6/ssl.py", line 203, in sendall
    v = self.send(data[count:])
  File "/usr/lib64/python2.6/ssl.py", line 174, in send
    v = self._sslobj.write(data)
TypeError: write() argument 1 must be string or read-only buffer, not bytearray

**Comment by tabuniie** [comment]
I hit the same issue (using Python 2.6.6).

I got around it by editing pytumblr/request.py, changing line 110 from:

        r = urllib2.Request(url, bytearray(body), headers)

to

        r = urllib2.Request(url, bytes(body), headers)

**Comment by morganpdx** [comment]
Same issue here as well.  Fix from @tabuniie resolved the problem.

**Comment by jasonpenny** [comment]
With the recent changes merged, this should no longer be an issue
